import type { Metadata } from "next";
import "./globals.css";
import "./components/layout/Footer";
import "./components/layout/Header";
import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";

export const metadata: Metadata = {
  title: "Hackit Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">

      <body className="background-image">
        {/* <Header/> */}
          {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
