import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hackit Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="background-image">
        {children}
      </body>
    </html>
  );
}
